# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Ensures our latest SDK changes remain compatible with the latest OP-TEE
# repository code
name: Test in OP-TEE Repo

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  # Run test on AMD64 host
  test-on-amd64-host:
    uses: ./.github/workflows/reuse_test_in_optee_repo.yml
    with:
      runs-on: ubuntu-latest
      container: ghcr.io/ivila/teaclave-trustzone-sdk-ci-runner:ubuntu-24.04

  # Run test on ARM64 host
  test-on-arm64-host:
    uses: ./.github/workflows/reuse_test_in_optee_repo.yml
    with:
      runs-on: ubuntu-24.04-arm
      container: ghcr.io/ivila/teaclave-trustzone-sdk-ci-runner:ubuntu-24.04
